/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import java.awt.Color;
import javax.swing.JColorChooser;
import theorie.du.graphe.Pan;
import theorie.du.graphe.Sommet;
import theorie.du.graphe.TheorieDuGraphe;

/**
 *
 * @author MouadC
 */
public class Color_Dialogue extends javax.swing.JDialog {
    Color sommetColor=Sommet.sommetCOLOR;
    Color indiceCOLOR=Sommet.indiceCOLOR;
    Color arcCOLOR=Sommet.arcCOLOR;
    Color indiceArcCOLOR=Sommet.indiceArcCOLOR;
    Color BackndColor=Pan.BackndColor;
    TheorieDuGraphe fr;
    /**
     * Creates new form Color_Dialogue
     */
    public Color_Dialogue(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        fr=(TheorieDuGraphe) parent;
        initComponents();
        sommetCouleur.setBackground(Sommet.defaultSommetCOLOR);
        indiceCouleur.setBackground(indiceCOLOR);
        arcCouleur.setBackground(arcCOLOR);
        indiceArcCouleur.setBackground(indiceArcCOLOR);
        BackndCouleur.setBackground(BackndColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sommetCouleur = new javax.swing.JButton();
        indiceCouleur = new javax.swing.JButton();
        arcCouleur = new javax.swing.JButton();
        indiceArcCouleur = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        BackndCouleur = new javax.swing.JButton();

        setTitle("Les couleurs du graphe");
        setBackground(new java.awt.Color(153, 153, 153));

        sommetCouleur.setText("Choisir un couleur pour le sommet");
        sommetCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sommetCouleurActionPerformed(evt);
            }
        });

        indiceCouleur.setText("Choisir un couleur pour l'indice de sommet");
        indiceCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiceCouleurActionPerformed(evt);
            }
        });

        arcCouleur.setText("Choisir un couleur pour l'arc");
        arcCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcCouleurActionPerformed(evt);
            }
        });

        indiceArcCouleur.setText("Choisir un couleur pour l'indice d'arc");
        indiceArcCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiceArcCouleurActionPerformed(evt);
            }
        });

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        BackndCouleur.setText("Choisir un couleur pour votre Background");
        BackndCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackndCouleurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sommetCouleur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indiceCouleur, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(arcCouleur, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(indiceArcCouleur, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Valider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Annuler))
                    .addComponent(BackndCouleur, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(sommetCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(indiceCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(arcCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(indiceArcCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BackndCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indiceArcCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiceArcCouleurActionPerformed
        // TODO add your handling code here:
        JColorChooser jcc=new JColorChooser();
        Color color=jcc.showDialog(null, "S'il vous plait, choisir un couleur pour votre indiceArcCOLOR", Sommet.indiceArcCOLOR);
        Sommet.indiceArcCOLOR=color;
        indiceArcCouleur.setBackground(color);
        fr.getPanel().repaint();
    }//GEN-LAST:event_indiceArcCouleurActionPerformed

    private void arcCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcCouleurActionPerformed
        // TODO add your handling code here:
        JColorChooser jcc=new JColorChooser();
        Color color=jcc.showDialog(null, "S'il vous plait, choisir un couleur pour votre arcCOLOR", Sommet.arcCOLOR);
        Sommet.arcCOLOR=color;
        arcCouleur.setBackground(color);
        fr.getPanel().repaint();
    }//GEN-LAST:event_arcCouleurActionPerformed

    private void indiceCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiceCouleurActionPerformed
        // TODO add your handling code here:
        JColorChooser jcc=new JColorChooser();
        Color color=jcc.showDialog(null, "S'il vous plait, choisir un couleur pour votre indiceCOLOR", Sommet.indiceCOLOR);
        Sommet.indiceCOLOR=color;
        indiceCouleur.setBackground(color);
        fr.getPanel().repaint();
    }//GEN-LAST:event_indiceCouleurActionPerformed

    private void sommetCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sommetCouleurActionPerformed
        // TODO add your handling code here:
        JColorChooser jcc=new JColorChooser();
        Color color=jcc.showDialog(null, "S'il vous plait, choisir un couleur pour votre sommetCOLOR", Sommet.sommetCOLOR);
        Sommet.sommetCOLOR=color;
        Sommet.defaultSommetCOLOR=color;
        sommetCouleur.setBackground(color);
        fr.getPanel().repaint();
    }//GEN-LAST:event_sommetCouleurActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        Sommet.sommetCOLOR=this.sommetColor;
        Sommet.indiceCOLOR=this.indiceCOLOR;
        Sommet.arcCOLOR=this.arcCOLOR;
        Sommet.indiceArcCOLOR=this.indiceArcCOLOR;
        this.setVisible(false);
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ValiderActionPerformed

    private void BackndCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackndCouleurActionPerformed
        // TODO add your handling code here:
        JColorChooser jcc=new JColorChooser();
        Color color=jcc.showDialog(null, "S'il vous plait, choisir un couleur pour votre Background", Sommet.sommetCOLOR);
        Pan.BackndColor=color;
        BackndCouleur.setBackground(color);
        TheorieDuGraphe.PATH="";
        fr.getPanel().repaint();
    }//GEN-LAST:event_BackndCouleurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Color_Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Color_Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Color_Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Color_Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Color_Dialogue dialog = new Color_Dialogue(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton BackndCouleur;
    private javax.swing.JButton Valider;
    private javax.swing.JButton arcCouleur;
    private javax.swing.JButton indiceArcCouleur;
    private javax.swing.JButton indiceCouleur;
    private javax.swing.JButton sommetCouleur;
    // End of variables declaration//GEN-END:variables
}
